### ISSUE TITLE
Some fields not shown in dataset display

### ISSUE THREAD

**Issue by mapgeek37** [tk-technologies/ckanext-dfo#29]
Fields in Basic Information section that are not showing up in the dataset display:
- notes, maintainer_email, name, owner_org (everything under Basic Information should be visible near the top when a user browses the dataset)
They do have a display_snippet, so I'm not sure why this is happening.

**Comment by TkTech** [comment]
Broken by a343a793e1d89f3b

**Comment by mapgeek37** [comment]
Fixed in `ckanext/dfo/templates/package/snippets/additional_info.html`
